### ISSUE TITLE
V 1.0.7 Failed to create AuditLogEvent for audit log

### ISSUE THREAD

**Issue by confile** [robertoschwald/grails-audit-logging-plugin#108] opened 2015-11-01 18:49 UTC
Setup: Grails 2.4.5. MySQL

After updating from 1.0.5 to 1.0.7 I get the following error when an audit log event should be created: 

```
Error |
2015-11-01 19:46:56,738 [http-nio-8080-exec-3] ERROR util.JDBCExceptionReporter  - Field 'id' doesn't have a default value
Error |
2015-11-01 19:46:56,820 [http-nio-8080-exec-3] ERROR auditable.AuditLogListener  - Failed to create AuditLogEvent for audit log Sun Nov 01 19:46:56 CET 2015 user confile UPDATE majestella.Hotel id:2aa3bfac3f4ffbbf83 version:27: Hibernate operation: could not insert: [org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogEvent]; SQL [insert into audit_log (actor, class_name, date_created, event_name, last_updated, new_value, old_value, persisted_object_id, persisted_object_version, property_name, uri) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Field 'id' doesn't have a default value; nested exception is java.sql.SQLException: Field 'id' doesn't have a default value

```

**Comment by robertoschwald** [comment] 2015-11-04 14:19
Do you have an idMapping configured for the plugin in your Config.groovy?

**Comment by robertoschwald** [comment] 2015-11-04 14:22
Duplicate of #104

**Closed by robertoschwald** 2015-11-04 14:22 UTC

**Comment by confile** [comment] 2015-11-04 16:40
@robertoschwald No I do not have a idMapping.
