### ISSUE TITLE
Plugin on Update causes No Property is found

### ISSUE THREAD

**Issue by ijafir** [robertoschwald/grails-audit-logging-plugin#105] opened 2015-09-29 21:45 UTC
Using the plugin with mongodb, on a domain update, the audit log is causing the following error

org.codehaus.groovy.grails.exceptions.InvalidPropertyException: No property found for name [classname] for class [classname]

the Set<String> dirtyProperties = domain.dirtyPropertyNames ?: []
line of code adds the class name as the a dirty property.

**Comment by ijafir** [comment] 2015-09-30 20:55
Exact error: ERROR auditable.AuditLogListenerUtil  - Audit plugin unable to process update event for com.pilrhealth.security.User
org.codehaus.groovy.grails.exceptions.InvalidPropertyException: No property found for name [com.user.User] for class [class com.user.User]
	at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:47)
	at org.grails.datastore.mapping.engine.EntityPersister.cancelUpdate(EntityPersister.java:270)
	at org.grails.datastore.mapping.engine.NativeEntryEntityPersister$2.run(NativeEntryEntityPersister.java:862)
	at org.grails.datastore.mapping.core.impl.PendingOperationExecution.executePendingOperation(PendingOperationExecution.java:33)
	at org.grails.datastore.mapping.core.AbstractSession.flushPendingOperations(AbstractSession.java:364)
	at org.grails.datastore.mapping.core.AbstractSession.flushPendingUpdates(AbstractSession.java:343)
	at org.grails.datastore.mapping.core.AbstractSession.flush(AbstractSession.java:263)
	at org.grails.datastore.mapping.mongo.MongoSession.flush(MongoSession.java:126)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:197)
	at org.grails.datastore.gorm.GormInstanceApi$_save_closure5.doCall(GormInstanceApi.groovy:162)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:302)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:161)

**Comment by robertoschwald** [comment] 2015-10-01 06:13
Duplicate of #103

**Closed by robertoschwald** 2015-10-01 06:13 UTC
Labels: Duplicate
