### ISSUE TITLE
oldValue not logged for hasMany associations

### ISSUE THREAD

**Issue by phibo23** [robertoschwald/grails-audit-logging-plugin#112] opened 2015-12-16 08:50 UTC
is there a way to achieve this?

![bildschirmfoto 2015-12-16 um 09 45 51](https://cloud.githubusercontent.com/assets/1328782/11836309/2464c38a-a3da-11e5-9f3f-3fe7495b6eaf.png)

**Comment by robertoschwald** [comment] 2015-12-29 17:52
Duplicate of #42

**Closed** 2015-12-29 17:52 UTC
